name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*
      - test-release.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          draft: true
          # (required) GitHub token for creating GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          # - os: ubuntu-22.04
          #   target: x86_64-unknown-linux-musl
          # - os: ubuntu-22.04
          #   target: aarch64-unknown-linux-gnu
          # - os: ubuntu-22.04
          #   target: aarch64-unknown-linux-musl
          - os: macos-12
            target: x86_64-apple-darwin
          - os: macos-12
            target: aarch64-apple-darwin
          - os: windows-2022
            target: x86_64-pc-windows-msvc
          - os: windows-2022
            target: x86_64-pc-windows-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.os }}-${{ matrix.target }}-rust
          cache-targets: true
          cache-on-failure: false
      - name: Install native dependencies
        if: runner.os == 'Linux'
        run: sudo apt install libasound2-dev binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu
      - name: Publish to crates.io
        if: matrix.os == 'ubuntu-22.04' && matrix.target == 'x86_64-unknown-linux-gnu'
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: aspeak
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.target }}
